sudo: required
language: c
env:
  global:
    - BROKENDNS=1

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-flask doxygen valgrind libpcap-dev python-pip cmake build-essential pkg-config libglib2.0-dev resource-agents python-gi python-netaddr python-demjson openjdk-7-jre
  - sudo -H pip install --upgrade pip
  - sudo -H pip install ctypesgen testify flask getent py2neo
before_script:
  - sudo $TRAVIS_BUILD_DIR/buildtools/ci/install_neo4j
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo $TRAVIS_BUILD_DIR/buildtools/ci/install_libsodium
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
script:
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - neoauth neo4j neo4j neo4j 2>&1 || true
  - "$TRAVIS_BUILD_DIR/discovery_agents/netconfig"
  - cd $TRAVIS_BUILD_DIR
  - cd ..
  - mkdir root_of_binary_tree
  - cd root_of_binary_tree
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - cmake $TRAVIS_BUILD_DIR
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo make install
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo ldconfig /usr/lib/x86_64-linux-gnu/assimilation
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo cpack
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo dpkg -i *.deb
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo /etc/init.d/nanoprobe stop
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo /etc/init.d/cma stop
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - sudo assimcli genkeys
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - cd $TRAVIS_BUILD_DIR/cma
  - grep -n dbms.security /var/lib/neo4j/conf/neo4j-server.properties /dev/null
  - neoauth neo4j neo4j neo4j 2>&1 || true
  - sudo testify -v tests
  - cd $TRAVIS_BUILD_DIR
